//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionDuMaterielDb.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employe
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> DateEntree { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public string EntreeDescription { get; set; }
        public Nullable<System.DateTime> DateSortie { get; set; }
        public string SortieDescription { get; set; }
        public int MeubleId { get; set; }
    
        public virtual Meuble Meuble { get; set; }
    }
}
