//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionDuMaterielDb.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employe()
        {
            this.Meubles = new HashSet<Meuble>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> DateEntree { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public string EntreeDescription { get; set; }
        public Nullable<System.DateTime> DateSortie { get; set; }
        public string SortieDescription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Meuble> Meubles { get; set; }
    }
}
