//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionDuMaterielDb.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GestionDuMaterielEntities : DbContext
    {
        public GestionDuMaterielEntities()
            : base("name=GestionDuMaterielEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CodeBarre> CodeBarres { get; set; }
        public virtual DbSet<Meuble> Meubles { get; set; }
        public virtual DbSet<Piece> Pieces { get; set; }
        public virtual DbSet<Plan> Plans { get; set; }
        public virtual DbSet<Ronde> Rondes { get; set; }
        public virtual DbSet<TypeMateriel> TypeMateriels { get; set; }
        public virtual DbSet<Employe> Employes { get; set; }
        public virtual DbSet<Materiel> Materiels { get; set; }
        public virtual DbSet<PresenceMateriel> PresenceMateriels { get; set; }
    }
}
