//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionDuMaterielDb.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materiel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Materiel()
        {
            this.PresenceMateriels = new HashSet<PresenceMateriel>();
        }
    
        public int Id { get; set; }
        public int TypeMaterielId { get; set; }
        public string Description { get; set; }
        public string CodeBarre { get; set; }
        public Nullable<System.DateTime> Entree { get; set; }
        public Nullable<System.DateTime> Sortie { get; set; }
        public string DescriptionEntree { get; set; }
        public string DescriptionSortie { get; set; }
        public Nullable<System.DateTime> Achat { get; set; }
        public Nullable<bool> Garantie { get; set; }
        public Nullable<System.DateTime> GarantieEcheance { get; set; }
        public Nullable<decimal> PrixAchat { get; set; }
        public Nullable<System.DateTime> DateDernierApercu { get; set; }
        public string CommentaireDernierApercu { get; set; }
    
        public virtual TypeMateriel TypeMateriel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PresenceMateriel> PresenceMateriels { get; set; }
    }
}
